### Listar todos os eventos (HTML)
GET http://localhost:3000/events


Accept: application/json

### Criar um novo evento (FORM)
Content-Type: application/x-www-form-urlencoded

title=Evento+Teste&description=Descrição+do+evento&creator_id=1&status=Ativo&event_date=2025-06-01


{
  "title": "Evento de Teste",
  "description": "Descrição do evento de teste",
  "creator_id": 1,
  "status": "Ativo",
  "event_date": "2025-06-01"
}

GET: http://localhost:3000
